export const currentUserActionTypes = {
  FETCH_CURRENT_USER_REQUEST: "FETCH_CURRENT_USER_REQUEST",
  FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_FAILURE: "FETCH_CURRENT_USER_FAILURE",
  SET_CURRENT_USER_SUCCESS: "SET_CURRENT_USER_SUCCESS",
  SET_CURRENT_USER_FAILURE: "SET_CURRENT_USER_FAILURE",
  SET_CURRENT_USER_GOAL_SUCCESS: "SET_CURRENT_USER_GOAL_SUCCCESS",
  SET_CURRENT_USER_GOAL_FAILURE: "SET_CURRENT_USER_GOAL_FAILURE",
  ADD_CURRENT_USER_FOOD_SUCCESS: "ADD_CURRENT_USER_FOOD_SUCCESS",
  ADD_CURRENT_USER_FOOD_FAILURE: "ADD_CURRENT_USER_FOOD_FAILURE",
  LOGIN_FAILURE: "LOGIN_FAILURE",
};
